"""empty message

Revision ID: 9d0a424f9e32
Revises: b4192473b93b
Create Date: 2018-03-16 14:21:58.368790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d0a424f9e32'
down_revision = 'b4192473b93b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'Notification_transaction_icon_id_fkey', 'Notification', type_='foreignkey')
    op.create_foreign_key(None, 'Notification', 'Icon', ['transaction_icon_id'], ['id'], ondelete='SET NULL')
    op.alter_column('User', 'mobile_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'mobile_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'Notification', type_='foreignkey')
    op.create_foreign_key(u'Notification_transaction_icon_id_fkey', 'Notification', 'Icon', ['transaction_icon_id'], ['id'])
    # ### end Alembic commands ###
