"""empty message

Revision ID: b4192473b93b
Revises: e2ce13828dbd
Create Date: 2018-03-15 03:16:58.346608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4192473b93b'
down_revision = 'e2ce13828dbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'AdmissionType_school_id_fkey', 'AdmissionType', type_='foreignkey')
    op.create_foreign_key(None, 'AdmissionType', 'User', ['school_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(u'DriverInfo_admission_type_id_fkey', 'DriverInfo', type_='foreignkey')
    op.create_foreign_key(None, 'DriverInfo', 'AdmissionType', ['admission_type_id'], ['id'], ondelete='SET NULL')
    op.alter_column('FreeRide', 'token',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('FreeRide', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(u'FreeRide_user_id_fkey', 'FreeRide', type_='foreignkey')
    op.create_foreign_key(None, 'FreeRide', 'User', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(u'Notification_sender_id_fkey', 'Notification', type_='foreignkey')
    op.drop_constraint(u'Notification_recipient_id_fkey', 'Notification', type_='foreignkey')
    op.create_foreign_key(None, 'Notification', 'User', ['sender_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'Notification', 'User', ['recipient_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(u'Transaction_sender_wallet_id_fkey', 'Transaction', type_='foreignkey')
    op.drop_constraint(u'Transaction_receiver_id_fkey', 'Transaction', type_='foreignkey')
    op.drop_constraint(u'Transaction_receiver_wallet_id_fkey', 'Transaction', type_='foreignkey')
    op.drop_constraint(u'Transaction_sender_id_fkey', 'Transaction', type_='foreignkey')
    op.create_foreign_key(None, 'Transaction', 'Wallet', ['receiver_wallet_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'Transaction', 'User', ['sender_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'Transaction', 'Wallet', ['sender_wallet_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'Transaction', 'User', ['receiver_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(u'User_user_type_id_fkey', 'User', type_='foreignkey')
    op.create_foreign_key(None, 'User', 'UserType', ['user_type_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'User', type_='foreignkey')
    op.create_foreign_key(u'User_user_type_id_fkey', 'User', 'UserType', ['user_type_id'], ['id'])
    op.drop_constraint(None, 'Transaction', type_='foreignkey')
    op.drop_constraint(None, 'Transaction', type_='foreignkey')
    op.drop_constraint(None, 'Transaction', type_='foreignkey')
    op.drop_constraint(None, 'Transaction', type_='foreignkey')
    op.create_foreign_key(u'Transaction_sender_id_fkey', 'Transaction', 'User', ['sender_id'], ['id'])
    op.create_foreign_key(u'Transaction_receiver_wallet_id_fkey', 'Transaction', 'Wallet', ['receiver_wallet_id'], ['id'])
    op.create_foreign_key(u'Transaction_receiver_id_fkey', 'Transaction', 'User', ['receiver_id'], ['id'])
    op.create_foreign_key(u'Transaction_sender_wallet_id_fkey', 'Transaction', 'Wallet', ['sender_wallet_id'], ['id'])
    op.drop_constraint(None, 'Notification', type_='foreignkey')
    op.drop_constraint(None, 'Notification', type_='foreignkey')
    op.create_foreign_key(u'Notification_recipient_id_fkey', 'Notification', 'User', ['recipient_id'], ['id'])
    op.create_foreign_key(u'Notification_sender_id_fkey', 'Notification', 'User', ['sender_id'], ['id'])
    op.drop_constraint(None, 'FreeRide', type_='foreignkey')
    op.create_foreign_key(u'FreeRide_user_id_fkey', 'FreeRide', 'User', ['user_id'], ['id'])
    op.alter_column('FreeRide', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('FreeRide', 'token',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'DriverInfo', type_='foreignkey')
    op.create_foreign_key(u'DriverInfo_admission_type_id_fkey', 'DriverInfo', 'AdmissionType', ['admission_type_id'], ['id'])
    op.drop_constraint(None, 'AdmissionType', type_='foreignkey')
    op.create_foreign_key(u'AdmissionType_school_id_fkey', 'AdmissionType', 'User', ['school_id'], ['id'])
    # ### end Alembic commands ###
