"""empty message

Revision ID: b89f1e4909eb
Revises: 08f01a86b75b
Create Date: 2018-05-14 21:56:37.634137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b89f1e4909eb'
down_revision = '08f01a86b75b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'DriverInfo_driver_id_fkey', 'DriverInfo', type_='foreignkey')
    op.create_foreign_key(None, 'DriverInfo', 'User', ['driver_id'], ['id'], ondelete='SET NULL')
    op.add_column('User', sa.Column('current_ride', sa.JSON(), nullable=True))
    op.drop_constraint(u'User_school_id_fkey', 'User', type_='foreignkey')
    op.create_foreign_key(None, 'User', 'SchoolInfo', ['school_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'User', type_='foreignkey')
    op.create_foreign_key(u'User_school_id_fkey', 'User', 'SchoolInfo', ['school_id'], ['id'])
    op.drop_column('User', 'current_ride')
    op.drop_constraint(None, 'DriverInfo', type_='foreignkey')
    op.create_foreign_key(u'DriverInfo_driver_id_fkey', 'DriverInfo', 'User', ['driver_id'], ['id'])
    # ### end Alembic commands ###
