"""empty message

Revision ID: c8edf8c9e8ce
Revises: 2d4641f7b704
Create Date: 2018-04-01 09:03:22.367458

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects.postgresql import ENUM


# revision identifiers, used by Alembic.
revision = 'c8edf8c9e8ce'
down_revision = '2d4641f7b704'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    authenticationtype = ENUM('email', 'facebook', 'google', name='authenticationtype')
    authenticationtype.create(op.get_bind())

    op.add_column('User', sa.Column('authentication_type', ENUM('email', 'facebook', 'google', name='authenticationtype'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'authentication_type')
    # ### end Alembic commands ###
