"""empty message

Revision ID: e2ce13828dbd
Revises: 
Create Date: 2018-03-11 14:38:25.625713

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects.postgresql import ENUM


# revision identifiers, used by Alembic.
revision = 'e2ce13828dbd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Icon',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('icon', sa.String(), nullable=False),
    sa.Column('operation_type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operation_type')
    )
    op.create_table('PercentagePrice',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('UserType',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('User',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_type_id', sa.String(), nullable=True),
    sa.Column('firstname', sa.String(length=30), nullable=False),
    sa.Column('lastname', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('mobile_number', sa.String(), nullable=True),
    sa.Column('authorization_code', sa.String(), nullable=True),
    sa.Column('authorization_code_status', sa.Boolean(), nullable=True),
    sa.Column('number_of_rides', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_type_id'], ['UserType.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('authorization_code'),
    sa.UniqueConstraint('email')
    )
    op.create_table('AdmissionType',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('admission_type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('school_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admission_type'),
    sa.UniqueConstraint('school_id')
    )
    op.create_table('FreeRide',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('free_ride_type', ENUM('social_share_type', name='freeridetype', create_type=False), nullable=False),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('token_status', sa.Boolean(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('Notification',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('recipient_id', sa.String(), nullable=True),
    sa.Column('sender_id', sa.String(), nullable=True),
    sa.Column('transaction_icon_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['User.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['User.id'], ),
    sa.ForeignKeyConstraint(['transaction_icon_id'], ['Icon.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('SchoolInfo',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('school_id', sa.String(), nullable=True),
    sa.Column('account_number', sa.String(), nullable=True),
    sa.Column('bank_name', sa.String(), nullable=True),
    sa.Column('mobile_number', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id')
    )
    op.create_table('Wallet',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('wallet_amount', sa.Float(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('DriverInfo',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('car_model', sa.String(), nullable=True),
    sa.Column('left_image', sa.String(), nullable=True),
    sa.Column('right_image', sa.String(), nullable=True),
    sa.Column('front_image', sa.String(), nullable=True),
    sa.Column('back_image', sa.String(), nullable=True),
    sa.Column('plate_number', sa.String(), nullable=True),
    sa.Column('admin_confirmed', sa.Boolean(), nullable=True),
    sa.Column('bank_name', sa.String(), nullable=True),
    sa.Column('account_number', sa.String(), nullable=True),
    sa.Column('driver_id', sa.String(), nullable=True),
    sa.Column('admission_type_id', sa.String(), nullable=True),
    sa.Column('number_of_rides', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admission_type_id'], ['AdmissionType.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('driver_id')
    )
    op.create_table('Transaction',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transaction_detail', sa.String(), nullable=False),
    sa.Column('type_of_operation', ENUM('borrow_type', 'cancel_type', 'wallet_type', 'ride_type', 'transfer_type', name='operationtype', create_type=False), nullable=False),
    sa.Column('type_of_transaction', ENUM('credit_type', 'debit_type', 'both_types', name='transactiontype', create_type=False), nullable=False),
    sa.Column('cost_of_transaction', sa.Float(), nullable=True),
    sa.Column('receiver_amount_before_transaction', sa.Float(), nullable=True),
    sa.Column('receiver_amount_after_transaction', sa.Float(), nullable=True),
    sa.Column('sender_amount_before_transaction', sa.Float(), nullable=True),
    sa.Column('sender_amount_after_transaction', sa.Float(), nullable=True),
    sa.Column('paystack_deduction', sa.Float(), nullable=True),
    sa.Column('receiver_id', sa.String(), nullable=True),
    sa.Column('sender_id', sa.String(), nullable=True),
    sa.Column('receiver_wallet_id', sa.String(), nullable=True),
    sa.Column('sender_wallet_id', sa.String(), nullable=True),
    sa.Column('transaction_date', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['User.id'], ),
    sa.ForeignKeyConstraint(['receiver_wallet_id'], ['Wallet.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['User.id'], ),
    sa.ForeignKeyConstraint(['sender_wallet_id'], ['Wallet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Transaction')
    op.drop_table('DriverInfo')
    op.drop_table('Wallet')
    op.drop_table('SchoolInfo')
    op.drop_table('Notification')
    op.drop_table('FreeRide')
    op.drop_table('AdmissionType')
    op.drop_table('User')
    op.drop_table('UserType')
    op.drop_table('PercentagePrice')
    op.drop_table('Icon')
    # ### end Alembic commands ###
